### ISSUE TITLE
How can I use `s3-proxy` as a stand alone service?

### ISSUE THREAD

**Issue by letusfly85** [4front/s3-proxy#1]
Hi, I want to use this library as a dummy s3 for CI.

If you know a way to run some scripts for dummy s3 service, please let me know.

**Comment by letusfly85** [comment]
sorry, I misunderstood.

**Comment by dvonlehman** [comment]
Hi @letusfly85, I'd recommend looking at https://www.npmjs.com/package/s3rver. I've used it successfully for just that purpose.

**Comment by letusfly85** [comment]
@dvonlehman 

Thank you for replying!
Great! I use s3rver :+1: 

(I was confused  because this repository README.md`s example, `import` section is not supported in my own nodejs environment...)

**Comment by letusfly85** [comment]
@dvonlehman 

Thank you, I succeeded creating s3-proxy docker image.

Thanks.

https://github.com/tripleW/docker-s3-proxy
